blank_issues_enabled: true
contact_links: []

issue_templates:
  - name: âœ¨ æ–°éœ€æ±‚ / New Feature
    description: æäº¤ä¸€ä¸ªæ–°çš„ç»„ä»¶ã€é¡µé¢æˆ–åŠŸèƒ½çš„å¼€å‘éœ€æ±‚
    labels: 
      - enhancement
      - needs-triage
    file: 1.feature.yml

  - name: ğŸ› Bug æŠ¥å‘Š / Bug Report
    description: æŠ¥å‘Šä¸€ä¸ªä½ é‡åˆ°çš„é—®é¢˜æˆ–å¼‚å¸¸è¡Œä¸º
    labels: 
      - bug
      - needs-triage
    file: 2.bug-report.yml
